INSERT INTO theme_item (id,
                        theme_id,
                        item_id,
                        item_img,
                        item_url,
                        item_title,
                        item_price,
						item_cost_price,
						item_discount,
                        item_sold_amount,
                        is_master_item,
                        master_item_tag,
                        like_count,
                        collect_count,
                        sort_nu,
                        is_destory,
                        destory_uid,
                        destory_at,
                        update_at,
                        update_uid,
                        create_at,
                        create_uid)
        VALUES (
                  nextval('theme_item_id_seq'),
                  100033,
                  100117,
                  '/uploads/minify/c9c26b40ccb04b37be67a42817257af61445397942627.jpg',
                  NULL,
                  '德国原产 CLASSIC深层修护经典护手霜100ml',
                  43.00,
				  48.00,
				  9.0,
                  NULL,
                  FALSE,
                  NULL,
                  NULL,
                  NULL,
                  NULL,
                  FALSE,
                  NULL,
                  NULL,
                  NULL,
                  NULL,
                  NULL,
                  NULL);

COMMIT;