INSERT INTO themes (id,
                    master_item_id,
                    title,
                    theme_desc,
                    start_at,
                    end_at,
                    theme_discount_up,
                    item_price_top,
                    item_price_low,
                    theme_img,
                    theme_url,
                    theme_tags,
                    item_count,
                    theme_tag_count,
                    sort_nu,
                    is_destory,
                    destory_uid,
                    destory_at,
                    update_at,
                    update_uid,
                    create_at,
                    create_uid)
        VALUES (
                  100033,
                  100117,
                  '★最值得购买的品质好货★',
                  '["仅剩9天", "★最值得购买的品质好货★", "19", "元起", "http://172.28.3.18:3008/uploads/minify/453388880c1840b484438c3b2190bfda1445403523918.jpg"]',
                  TO_TIMESTAMP ('10/01/2015 12:43:59.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  TO_TIMESTAMP ('01/01/2016 12:44:09.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
				  NULL,
                  519.00,
                  19.00,
                  '/uploads/shot/2a8acf163184439598ef3cefd5026d0f.png',
                  NULL,
                  NULL,
                  5,
                  NULL,
                  1,
                  FALSE,
                  NULL,
                  NULL,
                  NULL,
                  NULL,
                  TO_TIMESTAMP ('10/21/2015 13:04:09.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  100126);

COMMIT;